#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const rootDir = path.resolve(__dirname, '..');
const trackDefinitionsDir = path.join(rootDir, 'track_definitons');
const routingFile = path.join(trackDefinitionsDir, 'track_routing.yaml');
const outputFile = path.join(rootDir, 'src_new_interface', 'data', 'tracks.js');

function readYaml(filePath) {
  const contents = fs.readFileSync(filePath, 'utf8');
  return yaml.load(contents);
}

function ensureFileExists(filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`File not found: ${filePath}`);
  }
}

function main() {
  ensureFileExists(routingFile);
  const routingConfig = readYaml(routingFile);

  if (!routingConfig || !Array.isArray(routingConfig.routing)) {
    throw new Error('Invalid routing configuration: missing routing array');
  }

  const tracks = routingConfig.routing.map((trackConfig) => {
    const definitionPath = path.join(trackDefinitionsDir, trackConfig.file);
    ensureFileExists(definitionPath);

    const definition = readYaml(definitionPath);

    return {
      trackId: trackConfig.track_id,
      file: trackConfig.file,
      order: trackConfig.order ?? null,
      required: trackConfig.required ?? false,
      category: trackConfig.category ?? null,
      description: trackConfig.description || '',
      prerequisites: trackConfig.prerequisites || [],
      mutually_exclusive_with: trackConfig.mutually_exclusive_with || [],
      is_terminal: trackConfig.is_terminal ?? false,
      definition,
    };
  });

  const header = '// This file is auto-generated by scripts/generate-tracks.js\n';
  const contents = `${header}export default ${JSON.stringify(tracks, null, 2)};\n`;

  fs.writeFileSync(outputFile, contents, 'utf8');
  console.log(`Generated ${tracks.length} tracks → ${path.relative(rootDir, outputFile)}`);
}

main();
